Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,47 +20,25 @@ jobs:
         run: |
           echo "$YC_TOKEN" | docker login --username oauth --password-stdin cr.yandex
 
-      - name: Check Docker image existence in Container Registry
+      - name: Check if exists in Container Registry
         run: |
-          if docker pull ${{ secrets.REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest; then
-            echo "Docker image ${{ secrets.REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest found."
-          else
-            echo "Docker image ${{ secrets.REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest not found."
-            exit 1
+          if ! docker manifest inspect ${{ secrets.REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest; then
+            echo "Image not found!" && exit 1
           fi
 
-      - name: Check if some container is running
-        run: |
-          CONTAINER=$(docker ps -aqf "name=shri-infra")
-          if [ -n "$CONTAINER" ]; then
-            docker stop $CONTAINER
-            docker rm $CONTAINER
-          fi  
-
-      - name: Deploy to server
-        env:
-          SERVER_IP: ${{ secrets.VM_IP }}
-          SERVER_USER: ${{ secrets.VM_USER }}
-          SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_KEY }}
-        run: |
-          mkdir -p ~/.ssh
-          echo "$SSH_PRIVATE_KEY" > ~/.ssh/keys
-          chmod 600 ~/.ssh/keys
-          ssh -o StrictHostKeyChecking=no -i ~/.ssh/keys ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'
-            CONTAINER=$(docker ps -aqf "name=shri-infra")
-            if [ -n "$CONTAINER" ]; then
-              docker stop $CONTAINER
-              docker rm $CONTAINER
-            else
-              echo "This container does not exist yet."
-            fi  
+      - name: deploy VM
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.VM_IP }}
+          username: ${{ secrets.VM_USER }}
+          key: ${{ secrets.VM_SSH_KEY }}
+          script: |
+            echo ssh ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}
+            docker pull ${{ secrets.REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest
+            docker stop app || true
+            docker rm app || true
+            docker run -d --restart unless-stopped --name app -p 3000:3000 ${{ secrets.REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest
             
-            sudo docker pull ${{ secrets.REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest
-            sudo docker run -d -p 3000:3000 --name shri-infra ${{ secrets.REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest
-            
-            sleep 10
-          EOF
-
       - name: Set release date
         run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
         
