tests workflow check 3

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,32 +1,31 @@
 name: Running tests
-
-on:
-  pull_request:
-    branches:
-    - main
+  on:
+    pull_request:
+      branches:
+        - main
 
 jobs:
   test:
     runs-on: ubuntu-20.04
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@v2
+      - name: Checkout
+        uses: actions/checkout@v2
 
-    - name: Install depandencies
-      run: npm install
+      - name: Install dependencies
+        run: npm install
 
-    - name: Run linter
-      uses: npm run lint
+      - name: Run linter
+        run: npm run lint
 
-    - name: Run Jest tests
-      uses: npm run test
+      - name: Run Jest tests
+        run: npm run test
 
-    - name: Check Jest test results
-      run: |
-        if npm test | grep -q "Test Suites: 0 passed"; then
-          echo "Jest tests failed. Exiting."
-          exit 1
-        else
-          echo "Jest tests passed. Continuing."
-        fi
+      - name: Check Jest test results
+        run: |
+          if npm test | grep -q "Test Suites: 0 passed"; then
+            echo "Jest tests failed. Exiting."
+            exit 1
+          else
+            echo "Jest tests passed. Continuing."
+          fi
